
# Creating Maps in QGIS

Throughout this course you will use the same steps to create a map.

1. Prepare your data
2. Add your data to QGIS
3. Make sure your layer CRS values are correct, and choose a project CRS
4. Make your map look pretty
5. Use a Print Composer to export your map

We will introduce these steps not in the order listed above, but in order of difficulty (more or less). In Chapter \@ref(tutorial-mapofcanada) you will learn how to add data to the map, change the _Project CRS_, and use the _Print Composer_ to export a map from QGIS; in Chapter \@ref(tutorial-vectorstyle) and Chapter \@ref(tutorial-rasterstyle) you will learn how to style vector layers; in Chapter \@ref(tutorial-getdata) and Chapter \@ref(tutorial-dataprep) you will learn how to download freely available GIS data from the internet and prepare our own data to import to QGIS. In Chapter \@ref(tutorial-nssites) you will practice these five steps by creating a minimalist study stue map, and in Chapters \@ref(tutorial-createedit) and \@ref(tutorial-processing) you will learn how to create, edit, and process vector and raster layers.
